logging:
  level:
    com.reader.pdf: DEBUG
    org.apache.pdfbox: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

google:
  cloud:
    credentials:
      location: secrets/google-cloud-credentials.json
